services:
  db:
    image: mongo:noble
    container_name: media-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  minio:
    image: quay.io/minio/minio
    container_name: medias-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - medias:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

networks:
  default:
    name: med

volumes:
  db:
    name: local_mongo
    external: true
  medias:
    name: medias_s3
