services:
  db:
    image: mongo:noble
    container_name: media-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  minio:
    image: quay.io/minio/minio
    env_file:
      - .env
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
  auth:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: unless-stopped
    command: start-dev --import-realm --hostname ${KC_HOSTNAME}
    volumes:
      - ./realms:/opt/keycloak/data/import
    depends_on:
      - auth_db
  auth_db:
    image: postgres:18-alpine
    container_name: auth_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KC_DB}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - auth:/var/lib/postgresql

networks:
  default:
    name: med

volumes:
  db:
    # name: medias_db # prod volume
    name: medias_db_dev # dev volume
  minio:
    name: medias_minio
  auth:
    name: kc_auth
    external: true
